### ISSUE TITLE
New Maintained Repo for this plugin - please move

### ISSUE THREAD

**Issue by EYALIN** [apache/cordova-plugin-battery-status#108]
Instead of maintaining this plugin only for me, I published a new maintained plugin called "community-cordova-plugin-battery-status" (https://github.com/EYALIN/community-cordova-plugin-battery-status) which is maintained and will keep being.
please feel free to use it, and write me any feedback.
can be installed by using "cordova plugin add community-cordova-plugin-battery-status"
all Android and IOS recent issues are fixed there.

**Comment by breautek** [comment]
You just created a post https://github.com/apache/cordova-plugin-battery-status/issues/107, please stop spamming the issues thread here.

Like I said in the other thread, if you want to make an announcement of a community level plugin, a more appropriate place is at https://github.com/apache/cordova/discussions

**Comment by EYALIN** [comment]
@breautek sorry about it. added to the discussion.
We still need to add it here somewhere, so the community will have a fully maintained plugin.

**Comment by breautek** [comment]
> @breautek sorry about it. added to the discussion. We still need to add it here somewhere, so the community will have a fully maintained plugin.

I realise that it may feel like this plugin is not maintained or receiving enough attention, especially when issues or PRs have been left open for a significant amount of time with no progress, or sometimes no response. But until, there is a formal [vote](https://www.apache.org/foundation/voting.html) to sunset/deprecate the plugin, Apache must still treat the plugin has "maintained", therefore no text suggesting otherwise will be added to the repo at this time.

It's fine to maintain your own community version of a plugin, including Apache plugins, provided that you follow the conditions of the Apache license. I also have no issues with people advertising their community plugins, but I feel like that should be reserved to the Discussions board rather than the `Issues` of a project. Personally I also don't mind mentioning that the community version exist on issues if the community version contains a workaround to the issue in question.

**Comment by EYALIN** [comment]
@breautek really appreciate your detailed answer.
don't really know how it works, but it does not make sense to have updates once in a few years.
it will cause people not to use the Cordova plugins.
anyway, I will try to solve other people's problems and redirect them to my repo if it's ok with you.
it will not be advertising but offer them a plugin with a solution.

* I'm not doing this to earn money, I just need the plugins will be maintained for my own projects, and if more people will use it (they will, only if the plugin will be active) I will earn a much more efficient plugin.

thanks
